"""
v0.2 — Semantic Keyword Grouping.

This module takes the initial keyword-level architecture produced
by v02_architecture.py and asks Gemini to consolidate keywords
that share the same search intent.

The result is a page-level keyword map that will eventually drive
the final SEO site architecture.

Pipeline:

    v0.1 research
        ↓
    candidate keywords
        ↓
    Gemini semantic grouping
        ↓
    Python validation
        ↓
    final keyword groups
"""

import json
import os
import re
from typing import Any, Dict, List, Set

from core.llm import generate_json

from prompts.v02_prompts import (
    KeywordGroupingResponse,
    KEYWORD_GROUPING_SYSTEM_PROMPT,
)

# ============================================================
# PATHS
# ============================================================

V01_OUTPUT_PATH = os.path.join(
    "outputs",
    "page_opportunities.json",
)

V02_OUTPUT_DIR = os.path.join(
    "outputs",
    "v02",
)

GROUPING_OUTPUT_PATH = os.path.join(
    V02_OUTPUT_DIR,
    "keyword_groups.json",
)


# ============================================================
# FILE HELPERS
# ============================================================


def load_json_file(
    path: str,
) -> Dict[str, Any]:
    """
    Load a JSON object from disk.

    Args:
        path:
            JSON file path.

    Returns:
        Parsed JSON object.

    Raises:
        FileNotFoundError:
            If the file does not exist.

        ValueError:
            If the JSON is invalid or not an object.
    """

    if not os.path.exists(path):
        raise FileNotFoundError(f"Required file not found: {path}")

    try:
        with open(
            path,
            "r",
            encoding="utf-8",
        ) as file:
            data = json.load(file)

    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON file: {path}") from exc

    if not isinstance(
        data,
        dict,
    ):
        raise ValueError(f"Expected a JSON object in: {path}")

    return data


def load_v01_research() -> Dict[str, Any]:
    """
    Load the structured SEO research generated by v0.1.
    """

    return load_json_file(V01_OUTPUT_PATH)


# ============================================================
# NORMALIZATION
# ============================================================


def normalize_keyword(
    keyword: str,
) -> str:
    """
    Normalize keyword text for reliable comparison.

    This prevents differences in capitalization and whitespace
    from being treated as different keywords.
    """

    return re.sub(
        r"\s+",
        " ",
        str(keyword).strip().lower(),
    )


# ============================================================
# KEYWORD EXTRACTION
# ============================================================


def extract_cluster_keywords(
    cluster: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Extract keyword records from one v0.1 cluster.

    Returns:
        List of keyword records containing keyword metrics and
        intent information.
    """

    keywords = cluster.get(
        "keywords",
        [],
    )

    if not isinstance(
        keywords,
        list,
    ):
        return []

    result = []

    for item in keywords:
        if not isinstance(
            item,
            dict,
        ):
            continue

        keyword = item.get("keyword")

        if not keyword:
            continue

        result.append(item)

    return result


# ============================================================
# GEMINI INPUT
# ============================================================


def build_grouping_prompt(
    cluster: Dict[str, Any],
    keywords: List[Dict[str, Any]],
) -> str:
    """
    Build the prompt sent to Gemini for one topic cluster.

    Only information already produced by v0.1 is supplied to the
    model. This prevents the model from inventing additional SEO
    research.
    """

    keyword_payload = []

    for item in keywords:
        keyword_payload.append(
            {
                "keyword": item.get("keyword"),
                "volume": item.get("volume"),
                "competition": item.get("competition"),
                "competition_level": item.get("competition_level"),
                "intent": item.get("intent"),
                "is_question": item.get("is_question"),
            }
        )

    cluster_name = cluster.get("name", "")

    cluster_description = cluster.get("description", "")

    return (
        f"Topic cluster:\n"
        f"{cluster_name}\n\n"
        f"Cluster description:\n"
        f"{cluster_description}\n\n"
        f"Keywords discovered by v0.1:\n"
        f"{json.dumps(keyword_payload, indent=2)}\n\n"
        "Group these keywords into SEO pages based on search intent."
    )


# ============================================================
# GEMINI CALL
# ============================================================


def group_cluster_keywords(
    cluster: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Ask Gemini to group keywords for one cluster.

    Args:
        cluster:
            A v0.1 cluster containing keyword research.

    Returns:
        Dictionary containing the cluster name and Gemini's
        proposed keyword groups.
    """

    keywords = extract_cluster_keywords(cluster)

    if not keywords:
        return {
            "cluster": cluster.get("name", ""),
            "groups": [],
        }

    prompt = build_grouping_prompt(
        cluster,
        keywords,
    )

    response = generate_json(
        prompt=prompt,
        response_schema=KeywordGroupingResponse,
        system_instruction=KEYWORD_GROUPING_SYSTEM_PROMPT,
    )

    return {
        "cluster": cluster.get("name", ""),
        "groups": [group.model_dump() for group in response.groups],
    }


# ============================================================
# VALIDATION
# ============================================================


def validate_grouping(
    keywords: List[Dict[str, Any]],
    grouping: Dict[str, Any],
) -> None:
    """
    Validate Gemini's keyword grouping.

    Validation rules:

    - Every supplied keyword appears exactly once.
    - No unknown keyword is introduced.
    - Every primary keyword exists in the supplied data.
    - No keyword appears in multiple groups.

    Gemini is not trusted to enforce these constraints itself.
    Python performs the final verification.
    """

    supplied_keywords: Set[str] = {
        normalize_keyword(item["keyword"]) for item in keywords if item.get("keyword")
    }

    grouped_keywords: List[str] = []

    groups = grouping.get(
        "groups",
        [],
    )

    for group in groups:
        primary = group.get("primary_keyword")

        if not primary:
            raise ValueError("A keyword group is missing its primary keyword.")

        normalized_primary = normalize_keyword(primary)

        if normalized_primary not in supplied_keywords:
            raise ValueError(
                f"Gemini invented an unknown primary keyword: " f"'{primary}'"
            )

        grouped_keywords.append(normalized_primary)

        for secondary in group.get(
            "secondary_keywords",
            [],
        ):
            normalized_secondary = normalize_keyword(secondary)

            if normalized_secondary not in supplied_keywords:
                raise ValueError(
                    f"Gemini invented an unknown secondary keyword: " f"'{secondary}'"
                )

            grouped_keywords.append(normalized_secondary)

    grouped_set = set(grouped_keywords)

    duplicates = [
        keyword for keyword in grouped_set if grouped_keywords.count(keyword) > 1
    ]

    if duplicates:
        raise ValueError(
            "Gemini assigned keywords to multiple groups: " + ", ".join(duplicates)
        )

    missing = supplied_keywords - grouped_set

    if missing:
        raise ValueError(
            "Gemini did not assign these keywords to any group: "
            + ", ".join(sorted(missing))
        )


# ============================================================
# METADATA ENRICHMENT
# ============================================================


def build_keyword_lookup(
    keywords: List[Dict[str, Any]],
) -> Dict[str, Dict[str, Any]]:
    """
    Build a normalized keyword lookup table.

    This lets us attach the original v0.1 metrics to each final
    keyword group.
    """

    lookup = {}

    for item in keywords:
        keyword = item.get("keyword")

        if not keyword:
            continue

        lookup[normalize_keyword(keyword)] = item

    return lookup


def enrich_groups(
    grouping: Dict[str, Any],
    keywords: List[Dict[str, Any]],
) -> Dict[str, Any]:
    """
    Attach original v0.1 keyword metrics to the Gemini grouping.

    The LLM decides semantic relationships, while the original
    research remains the source of truth for keyword metrics.
    """

    lookup = build_keyword_lookup(keywords)

    enriched_groups = []

    for group in grouping.get(
        "groups",
        [],
    ):
        primary = group["primary_keyword"]

        all_keywords = [
            primary,
            *group.get(
                "secondary_keywords",
                [],
            ),
        ]

        keyword_records = []

        for keyword in all_keywords:
            source = lookup[normalize_keyword(keyword)]

            keyword_records.append(
                {
                    "keyword": source.get("keyword"),
                    "volume": source.get("volume"),
                    "competition": source.get("competition"),
                    "competition_level": source.get("competition_level"),
                    "cpc": source.get("cpc"),
                    "intent": source.get("intent"),
                    "is_question": source.get("is_question"),
                }
            )

        enriched_groups.append(
            {
                "group_id": group.get("group_id"),
                "primary_keyword": primary,
                "secondary_keywords": group.get(
                    "secondary_keywords",
                    [],
                ),
                "page_type": group.get("page_type"),
                "reasoning": group.get("reasoning"),
                "keywords": keyword_records,
            }
        )

    return {
        "cluster": grouping.get("cluster"),
        "groups": enriched_groups,
    }


# ============================================================
# FULL PIPELINE
# ============================================================


def build_keyword_groups(
    research: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Generate semantic keyword groups for every v0.1 cluster.

    Each cluster is processed independently to keep prompts small
    and ensure that unrelated topic clusters cannot accidentally
    share a page.
    """

    clusters = research.get(
        "clusters",
        [],
    )

    results = []

    for index, cluster in enumerate(
        clusters,
        start=1,
    ):
        if not isinstance(
            cluster,
            dict,
        ):
            continue

        cluster_name = cluster.get(
            "name",
            "Unknown",
        )

        print(
            f"\n[Cluster {index}/{len(clusters)}] "
            f"Grouping keywords for '{cluster_name}'..."
        )

        keywords = extract_cluster_keywords(cluster)

        print(f"  • Keywords supplied: " f"{len(keywords)}")

        if not keywords:
            print("  • No keywords found. Skipping.")

            results.append(
                {
                    "cluster": cluster_name,
                    "groups": [],
                }
            )

            continue

        try:
            grouping = group_cluster_keywords(cluster)

            validate_grouping(
                keywords,
                grouping,
            )

            enriched = enrich_groups(
                grouping,
                keywords,
            )

            print(f"  ✓ Generated " f"{len(enriched['groups'])} page groups")

            results.append(enriched)

        except Exception as exc:
            print(f"  ✗ Keyword grouping failed: {exc}")

            raise

    return {
        "version": "0.2",
        "grouping_method": "gemini_search_intent",
        "clusters": results,
    }


# ============================================================
# OUTPUT
# ============================================================


def save_keyword_groups(
    data: Dict[str, Any],
) -> None:
    """
    Save semantic keyword groups to the v0.2 output directory.
    """

    os.makedirs(
        V02_OUTPUT_DIR,
        exist_ok=True,
    )

    with open(
        GROUPING_OUTPUT_PATH,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            data,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# ENTRY POINT
# ============================================================


def run_v02_keyword_grouping() -> Dict[str, Any]:
    """
    Execute the semantic keyword grouping stage.

    Pipeline:

        load v0.1 research
             ↓
        group keywords with Gemini
             ↓
        validate response
             ↓
        attach original metrics
             ↓
        save keyword groups
    """

    print("\n" + "=" * 60)
    print("        V0.2 — SEMANTIC KEYWORD GROUPING")
    print("=" * 60)

    print("\n[Step 1] Loading v0.1 research...")

    research = load_v01_research()

    print("  ✓ Research loaded")

    print("\n[Step 2] Grouping keywords by search intent...")

    result = build_keyword_groups(research)

    total_groups = sum(len(cluster.get("groups", [])) for cluster in result["clusters"])

    total_keywords = sum(
        len(extract_cluster_keywords(cluster))
        for cluster in research.get("clusters", [])
    )

    print(f"\n  ✓ Total keywords processed: " f"{total_keywords}")

    print(f"  ✓ Total page groups: " f"{total_groups}")

    print("\n[Step 3] Saving keyword groups...")

    save_keyword_groups(result)

    print(f"  ✓ Saved: {GROUPING_OUTPUT_PATH}")

    print("\n" + "=" * 60)
    print("        SEMANTIC GROUPING COMPLETE")
    print("=" * 60)

    return result


if __name__ == "__main__":
    run_v02_keyword_grouping()
