"""
v0.2 — Site Foundation

This module begins the v0.2 phase of the SEO automation agent.

Responsibilities:
1. Load the structured output generated by v0.1.
2. Validate that the required research data exists.
3. Infer a high-level website profile from the v0.1 research.
4. Save the inferred profile for the remaining v0.2 pipeline.

This module intentionally does NOT generate the frontend yet.
It establishes the data contract between v0.1 and v0.2.
"""

import json
import os
from typing import Any, Dict, List, Optional


# ============================================================
# PATH CONFIGURATION
# ============================================================

# v0.1 currently writes page_opportunities.json directly inside
# the agent/outputs directory. We consume that existing output
# instead of changing the working v0.1 implementation.
V01_OUTPUT_PATH = os.path.join(
    "outputs",
    "page_opportunities.json",
)

# All new v0.2 artifacts will live in their own directory so that
# v0.1 outputs remain untouched.
V02_OUTPUT_DIR = os.path.join(
    "outputs",
    "v02",
)

SITE_PROFILE_PATH = os.path.join(
    V02_OUTPUT_DIR,
    "site_profile.json",
)


# ============================================================
# FILE HELPERS
# ============================================================

def ensure_v02_output_directory() -> None:
    """
    Create the v0.2 output directory if it does not already exist.

    This function is intentionally small and deterministic so that
    the v0.2 pipeline can safely be executed multiple times.
    """

    os.makedirs(
        V02_OUTPUT_DIR,
        exist_ok=True,
    )


def load_v01_research() -> Dict[str, Any]:
    """
    Load the structured research generated by v0.1.

    Returns:
        Dictionary containing the v0.1 page opportunity data.

    Raises:
        FileNotFoundError:
            If page_opportunities.json does not exist.

        ValueError:
            If the JSON file cannot be parsed or does not contain
            the expected top-level object.
    """

    if not os.path.exists(V01_OUTPUT_PATH):
        raise FileNotFoundError(
            f"v0.1 output was not found: {V01_OUTPUT_PATH}\n"
            "Run v0.1 research before starting v0.2."
        )

    try:
        with open(
            V01_OUTPUT_PATH,
            "r",
            encoding="utf-8",
        ) as file:
            data = json.load(file)

    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid JSON in v0.1 output: {V01_OUTPUT_PATH}"
        ) from exc

    if not isinstance(data, dict):
        raise ValueError(
            "v0.1 page_opportunities.json must contain a JSON object."
        )

    return data


# ============================================================
# VALIDATION
# ============================================================

def validate_v01_research(
    research: Dict[str, Any],
) -> None:
    """
    Validate the minimum data required by v0.2.

    v0.2 depends on the project information and cluster research
    produced by v0.1.

    Args:
        research:
            Parsed v0.1 research dictionary.

    Raises:
        ValueError:
            If required v0.1 fields are missing or malformed.
    """

    required_fields = [
        "project",
        "clusters",
    ]

    for field in required_fields:
        if field not in research:
            raise ValueError(
                f"Required v0.1 field is missing: '{field}'"
            )

    project = research["project"]

    if not isinstance(project, dict):
        raise ValueError(
            "v0.1 'project' field must be an object."
        )

    clusters = research["clusters"]

    if not isinstance(clusters, list):
        raise ValueError(
            "v0.1 'clusters' field must be a list."
        )

    if not clusters:
        raise ValueError(
            "v0.1 contains no topic clusters. "
            "v0.2 cannot build a site architecture without clusters."
        )


# ============================================================
# SITE PROFILE INFERENCE
# ============================================================

def _collect_project_text(
    research: Dict[str, Any],
) -> str:
    """
    Combine important project-level research fields into a single
    normalized text string.

    The resulting text is used by the deterministic heuristics
    that provide the initial site-model inference.
    """

    project = research.get("project", {})

    values = [
        project.get("core_topic", ""),
        project.get("target_audience", ""),
        project.get("site_goal", ""),
        project.get("geo_scope", ""),
        project.get("constraints", ""),
    ]

    return " ".join(
        str(value)
        for value in values
        if value
    ).lower()


def _collect_cluster_text(
    research: Dict[str, Any],
) -> str:
    """
    Combine cluster names and descriptions into normalized text.

    This gives the site-profile inference access to the broader
    research landscape rather than relying only on the project
    description.
    """

    cluster_text: List[str] = []

    for cluster in research.get("clusters", []):
        if not isinstance(cluster, dict):
            continue

        cluster_text.append(
            str(cluster.get("name", ""))
        )

        cluster_text.append(
            str(cluster.get("description", ""))
        )

    return " ".join(cluster_text).lower()


def infer_site_model(
    research: Dict[str, Any],
) -> str:
    """
    Infer the broad website model from v0.1 research.

    The supported models are:

        content
        ecommerce
        marketplace
        social
        saas
        hybrid

    This first implementation intentionally uses deterministic
    heuristics rather than an LLM. This makes the v0.2 foundation
    predictable and easy to test.

    A later iteration can introduce LLM reasoning where ambiguity
    exists.

    Args:
        research:
            Parsed and validated v0.1 research.

    Returns:
        Inferred site model.
    """

    text = (
        _collect_project_text(research)
        + " "
        + _collect_cluster_text(research)
    )

    ecommerce_terms = [
        "shop",
        "shopping",
        "product",
        "products",
        "buy",
        "store",
        "clothing",
        "fashion",
    ]

    social_terms = [
        "social",
        "community",
        "creator",
        "creators",
        "followers",
        "following",
        "profile",
        "post",
        "posts",
        "reels",
        "user-generated",
    ]

    marketplace_terms = [
        "marketplace",
        "seller",
        "sellers",
        "buyers",
        "vendors",
        "listing",
        "listings",
    ]

    saas_terms = [
        "software",
        "platform",
        "subscription",
        "dashboard",
        "workflow",
        "automation",
        "tool",
        "tools",
    ]

    content_terms = [
        "blog",
        "guide",
        "guides",
        "article",
        "articles",
        "content",
        "information",
        "education",
    ]

    scores = {
        "ecommerce": 0,
        "social": 0,
        "marketplace": 0,
        "saas": 0,
        "content": 0,
    }

    for term in ecommerce_terms:
        if term in text:
            scores["ecommerce"] += 1

    for term in social_terms:
        if term in text:
            scores["social"] += 1

    for term in marketplace_terms:
        if term in text:
            scores["marketplace"] += 1

    for term in saas_terms:
        if term in text:
            scores["saas"] += 1

    for term in content_terms:
        if term in text:
            scores["content"] += 1

    # If multiple product/social signals are strong, the website
    # is better represented as a hybrid platform.
    if (
        scores["social"] >= 2
        and scores["ecommerce"] >= 2
    ):
        return "hybrid"

    if (
        scores["marketplace"] >= 2
        and scores["social"] >= 2
    ):
        return "hybrid"

    highest_model = max(
        scores,
        key=scores.get,
    )

    highest_score = scores[highest_model]

    # If there is not enough evidence for a specialized model,
    # default to a content-oriented website because the current
    # SEO agent is fundamentally driven by content research.
    if highest_score == 0:
        return "content"

    return highest_model


def infer_primary_entities(
    research: Dict[str, Any],
) -> List[str]:
    """
    Infer the primary entities/topics represented by the website.

    The initial implementation derives these from topic cluster
    names. More sophisticated entity extraction can be introduced
    later without changing the v0.2 output contract.

    Args:
        research:
            Parsed v0.1 research.

    Returns:
        List of cluster names representing primary website entities.
    """

    entities: List[str] = []

    for cluster in research.get("clusters", []):
        if not isinstance(cluster, dict):
            continue

        name = cluster.get("name")

        if not name:
            continue

        name = str(name).strip()

        if name and name not in entities:
            entities.append(name)

    return entities


def build_site_profile(
    research: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build the complete v0.2 SiteProfile from v0.1 research.

    The output is intentionally JSON-serializable because it will
    become the input to later v0.2 stages such as architecture
    planning, page generation, URL planning, and SEO rules.

    Args:
        research:
            Parsed and validated v0.1 research.

    Returns:
        Dictionary containing the inferred site profile.
    """

    project = research.get(
        "project",
        {},
    )

    site_model = infer_site_model(
        research
    )

    entities = infer_primary_entities(
        research
    )

    profile = {
        "site_model": site_model,
        "primary_purpose": project.get(
            "site_goal",
            "",
        ),
        "target_audience": project.get(
            "target_audience",
            "",
        ),
        "primary_topic": project.get(
            "core_topic",
            "",
        ),
        "geo_scope": project.get(
            "geo_scope",
            "",
        ),
        "constraints": project.get(
            "constraints",
            "",
        ),
        "primary_entities": entities,
        "cluster_count": len(
            research.get(
                "clusters",
                [],
            )
        ),
        "source": "v01/page_opportunities.json",
        "version": "0.2",
    }

    return profile


# ============================================================
# OUTPUT
# ============================================================

def save_site_profile(
    profile: Dict[str, Any],
) -> None:
    """
    Save the generated SiteProfile to the v0.2 output directory.

    Args:
        profile:
            JSON-serializable site profile dictionary.
    """

    ensure_v02_output_directory()

    with open(
        SITE_PROFILE_PATH,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            profile,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# V0.2 ENTRY POINT
# ============================================================

def run_v02_site_foundation() -> Dict[str, Any]:
    """
    Execute the first stage of v0.2.

    Pipeline:

        load v0.1
            ↓
        validate v0.1
            ↓
        infer site profile
            ↓
        save site profile

    Returns:
        The generated SiteProfile dictionary.
    """

    print("\n" + "=" * 60)
    print("        SEO AUTOMATION AGENT — v0.2")
    print("        SITE FOUNDATION")
    print("=" * 60)

    print("\n[Step 1] Loading v0.1 research...")

    research = load_v01_research()

    print(
        f"  ✓ Loaded {V01_OUTPUT_PATH}"
    )

    print("\n[Step 2] Validating v0.1 research...")

    validate_v01_research(
        research
    )

    print("  ✓ v0.1 research is valid")

    print("\n[Step 3] Inferring website profile...")

    profile = build_site_profile(
        research
    )

    print(
        f"  ✓ Site model: {profile['site_model']}"
    )

    print(
        f"  ✓ Primary topic: "
        f"{profile['primary_topic']}"
    )

    print(
        f"  ✓ Clusters: "
        f"{profile['cluster_count']}"
    )

    print("\n[Step 4] Saving v0.2 site profile...")

    save_site_profile(
        profile
    )

    print(
        f"  ✓ Saved: {SITE_PROFILE_PATH}"
    )

    print("\n" + "=" * 60)
    print("        V0.2 FOUNDATION COMPLETE")
    print("=" * 60)

    return profile


if __name__ == "__main__":
    run_v02_site_foundation()