"""
v0.2 — Site Architecture Planner

This module converts the structured research produced by v0.1
into a machine-readable SEO site architecture.

Responsibilities:
1. Load v0.1 page opportunities.
2. Load the v0.2 SiteProfile.
3. Analyze clusters, keywords, and content gaps.
4. Create SEO page candidates.
5. Assign keywords to pages.
6. Establish a logical parent/child hierarchy.
7. Save the resulting architecture.

This module does NOT generate page content and does NOT create
the frontend. It only decides what pages the website should have.
"""

import json
import os
import re
from typing import Any, Dict, List, Optional


# ============================================================
# PATHS
# ============================================================

V01_OUTPUT_PATH = os.path.join(
    "outputs",
    "page_opportunities.json",
)

V02_OUTPUT_DIR = os.path.join(
    "outputs",
    "v02",
)

SITE_PROFILE_PATH = os.path.join(
    V02_OUTPUT_DIR,
    "site_profile.json",
)

ARCHITECTURE_PATH = os.path.join(
    V02_OUTPUT_DIR,
    "site_architecture.json",
)


# ============================================================
# FILE HELPERS
# ============================================================

def load_json_file(path: str) -> Dict[str, Any]:
    """
    Load a JSON file and return its parsed dictionary.

    Args:
        path:
            Path to the JSON file.

    Returns:
        Parsed JSON dictionary.

    Raises:
        FileNotFoundError:
            If the requested file does not exist.

        ValueError:
            If the file does not contain a valid JSON object.
    """

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"Required file was not found: {path}"
        )

    try:
        with open(
            path,
            "r",
            encoding="utf-8",
        ) as file:
            data = json.load(file)

    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid JSON file: {path}"
        ) from exc

    if not isinstance(data, dict):
        raise ValueError(
            f"Expected a JSON object in: {path}"
        )

    return data


def load_v01_research() -> Dict[str, Any]:
    """
    Load the page opportunity data generated by v0.1.
    """

    return load_json_file(
        V01_OUTPUT_PATH
    )


def load_site_profile() -> Dict[str, Any]:
    """
    Load the SiteProfile generated by the first v0.2 stage.
    """

    return load_json_file(
        SITE_PROFILE_PATH
    )


# ============================================================
# SLUGGING
# ============================================================

def slugify(value: str) -> str:
    """
    Convert human-readable text into a URL-safe slug.

    Example:

        "Festival and Concert Outfits"
        ->
        "festival-and-concert-outfits"

    Args:
        value:
            Text to convert.

    Returns:
        URL-safe lowercase slug.
    """

    value = value.lower().strip()

    value = re.sub(
        r"[^a-z0-9\s-]",
        "",
        value,
    )

    value = re.sub(
        r"\s+",
        "-",
        value,
    )

    value = re.sub(
        r"-+",
        "-",
        value,
    )

    return value.strip("-")


# ============================================================
# KEYWORD NORMALIZATION
# ============================================================

def normalize_keyword(
    keyword: str,
) -> str:
    """
    Normalize a keyword for comparison.

    This helps prevent duplicate keyword mappings caused by
    capitalization or whitespace differences.
    """

    return re.sub(
        r"\s+",
        " ",
        keyword.lower().strip(),
    )


def extract_cluster_keywords(
    cluster: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Extract keyword records from a v0.1 cluster.

    The function tolerates missing optional fields because v0.1
    may contain keyword records with different metric availability.
    """

    keywords = cluster.get(
        "keywords",
        [],
    )

    if not isinstance(
        keywords,
        list,
    ):
        return []

    result = []

    for item in keywords:
        if isinstance(
            item,
            str,
        ):
            result.append(
                {
                    "keyword": item,
                }
            )

        elif isinstance(
            item,
            dict,
        ):
            keyword = item.get(
                "keyword"
            )

            if keyword:
                result.append(
                    item
                )

    return result


# ============================================================
# PAGE TYPE INFERENCE
# ============================================================

def infer_page_type(
    keyword: str,
    cluster: Dict[str, Any],
) -> str:
    """
    Infer the most appropriate SEO page type for a keyword.

    This is intentionally conservative.

    The current implementation recognizes common informational
    and category-style patterns. More advanced page-type reasoning
    can later be delegated to the LLM.
    """

    normalized = normalize_keyword(
        keyword
    )

    question_starters = (
        "what ",
        "how ",
        "why ",
        "when ",
        "where ",
        "which ",
        "can ",
        "should ",
    )

    if normalized.startswith(
        question_starters
    ):
        return "guide"

    informational_terms = [
        "ideas",
        "guide",
        "tips",
        "inspiration",
        "how to",
        "what to wear",
        "examples",
    ]

    for term in informational_terms:
        if term in normalized:
            return "guide"

    return "category"


# ============================================================
# PRIORITY
# ============================================================

def determine_page_priority(
    keyword_data: Dict[str, Any],
) -> str:
    """
    Determine a basic page priority using available v0.1 metrics.

    Priority is deliberately conservative.

    If volume information is unavailable, the page receives
    medium priority rather than making an unsupported assumption.
    """

    volume = keyword_data.get(
        "volume"
    )

    competition_level = str(
        keyword_data.get(
            "competition_level",
            ""
        )
    ).lower()

    if isinstance(
        volume,
        (int, float),
    ):
        if volume >= 1000:
            if competition_level in {
                "low",
                "medium",
            }:
                return "high"

        if volume >= 300:
            return "medium"

        return "low"

    return "medium"


# ============================================================
# PAGE CREATION
# ============================================================

def create_cluster_root_page(
    cluster: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Create the root SEO page representing a topic cluster.

    Example:

        Festival and Concert Outfits

        becomes

        /festival-and-concert-outfits/
    """

    name = str(
        cluster.get(
            "name",
            ""
        )
    ).strip()

    slug = slugify(
        name
    )

    return {
        "id": f"cluster:{slug}",
        "title": name,
        "slug": slug,
        "url": f"/{slug}/",
        "page_type": "cluster",
        "cluster": name,
        "parent_page_id": None,
        "primary_keyword": None,
        "secondary_keywords": [],
        "intent": "mixed",
        "priority": "high",
        "indexable": True,
        "content_status": "planned",
    }


def create_keyword_page(
    keyword_data: Dict[str, Any],
    cluster: Dict[str, Any],
    parent_page_id: str,
) -> Dict[str, Any]:
    """
    Create an SEO page candidate from a keyword.

    Each page initially receives one primary keyword.

    Later we will add semantic keyword grouping so that multiple
    keywords with the same search intent share a single page.
    """

    keyword = str(
        keyword_data.get(
            "keyword",
            ""
        )
    ).strip()

    slug = slugify(
        keyword
    )

    cluster_name = str(
        cluster.get(
            "name",
            ""
        )
    ).strip()

    page_type = infer_page_type(
        keyword,
        cluster,
    )

    return {
        "id": f"keyword:{slug}",
        "title": keyword.title(),
        "slug": slug,
        "url": f"/{slug}/",
        "page_type": page_type,
        "cluster": cluster_name,
        "parent_page_id": parent_page_id,
        "primary_keyword": keyword,
        "secondary_keywords": [],
        "intent": keyword_data.get(
            "intent"
        ),
        "priority": determine_page_priority(
            keyword_data
        ),
        "indexable": True,
        "content_status": "planned",
    }


# ============================================================
# KEYWORD DEDUPLICATION
# ============================================================

def deduplicate_keywords(
    keywords: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Remove duplicate keyword records.

    Duplicate detection is based on normalized keyword text.
    """

    seen = set()

    unique = []

    for item in keywords:
        keyword = item.get(
            "keyword"
        )

        if not keyword:
            continue

        normalized = normalize_keyword(
            str(keyword)
        )

        if normalized in seen:
            continue

        seen.add(
            normalized
        )

        unique.append(
            item
        )

    return unique


# ============================================================
# ARCHITECTURE GENERATION
# ============================================================

def build_cluster_architecture(
    cluster: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build the page hierarchy for one topic cluster.

    The initial hierarchy is:

        Cluster
          ├── Keyword page
          ├── Keyword page
          └── Keyword page

    Later iterations will group semantically similar keywords
    so that one page can target multiple closely related queries.
    """

    cluster_page = create_cluster_root_page(
        cluster
    )

    keywords = extract_cluster_keywords(
        cluster
    )

    keywords = deduplicate_keywords(
        keywords
    )

    pages = [
        cluster_page
    ]

    for keyword_data in keywords:
        keyword = keyword_data.get(
            "keyword"
        )

        if not keyword:
            continue

        # Avoid creating a page whose slug is identical to the
        # cluster page.
        if slugify(
            str(keyword)
        ) == cluster_page["slug"]:
            continue

        page = create_keyword_page(
            keyword_data,
            cluster,
            cluster_page["id"],
        )

        pages.append(
            page
        )

    return {
        "cluster": cluster_page,
        "pages": pages,
    }


def build_site_architecture(
    research: Dict[str, Any],
    site_profile: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Build the complete SEO site architecture.

    Args:
        research:
            v0.1 page opportunity data.

        site_profile:
            v0.2 SiteProfile.

    Returns:
        Complete architecture containing clusters and pages.
    """

    clusters = research.get(
        "clusters",
        [],
    )

    all_pages = []

    cluster_architectures = []

    for cluster in clusters:
        if not isinstance(
            cluster,
            dict,
        ):
            continue

        architecture = build_cluster_architecture(
            cluster
        )

        cluster_architectures.append(
            architecture
        )

        all_pages.extend(
            architecture["pages"]
        )

    return {
        "version": "0.2",
        "site_profile": site_profile,
        "clusters": cluster_architectures,
        "pages": all_pages,
        "page_count": len(all_pages),
    }


# ============================================================
# VALIDATION
# ============================================================

def validate_architecture(
    architecture: Dict[str, Any],
) -> None:
    """
    Validate the generated site architecture.

    Checks:

    - page IDs are unique
    - URLs are unique
    - every child references an existing parent
    - indexable pages have URLs
    """

    pages = architecture.get(
        "pages",
        [],
    )

    page_ids = set()
    urls = set()

    for page in pages:
        page_id = page.get(
            "id"
        )

        url = page.get(
            "url"
        )

        if not page_id:
            raise ValueError(
                "Architecture contains a page without an ID."
            )

        if page_id in page_ids:
            raise ValueError(
                f"Duplicate page ID: {page_id}"
            )

        page_ids.add(
            page_id
        )

        if not url:
            raise ValueError(
                f"Page has no URL: {page_id}"
            )

        if url in urls:
            raise ValueError(
                f"Duplicate URL: {url}"
            )

        urls.add(
            url
        )

    for page in pages:
        parent_id = page.get(
            "parent_page_id"
        )

        if parent_id is not None:
            if parent_id not in page_ids:
                raise ValueError(
                    f"Page '{page['id']}' references "
                    f"missing parent '{parent_id}'."
                )


# ============================================================
# OUTPUT
# ============================================================

def save_architecture(
    architecture: Dict[str, Any],
) -> None:
    """
    Save the generated site architecture to disk.
    """

    os.makedirs(
        V02_OUTPUT_DIR,
        exist_ok=True,
    )

    with open(
        ARCHITECTURE_PATH,
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            architecture,
            file,
            indent=2,
            ensure_ascii=False,
        )


# ============================================================
# ENTRY POINT
# ============================================================

def run_v02_architecture() -> Dict[str, Any]:
    """
    Execute the v0.2 architecture-planning stage.

    Pipeline:

        load research
             ↓
        load SiteProfile
             ↓
        generate cluster architecture
             ↓
        validate
             ↓
        save architecture

    Returns:
        Generated architecture dictionary.
    """

    print("\n" + "=" * 60)
    print("        V0.2 — SITE ARCHITECTURE")
    print("=" * 60)

    print("\n[Step 1] Loading v0.1 research...")

    research = load_v01_research()

    print("  ✓ Research loaded")

    print("\n[Step 2] Loading SiteProfile...")

    site_profile = load_site_profile()

    print(
        f"  ✓ Site model: "
        f"{site_profile.get('site_model')}"
    )

    print("\n[Step 3] Building site architecture...")

    architecture = build_site_architecture(
        research,
        site_profile,
    )

    print(
        f"  ✓ Generated "
        f"{architecture['page_count']} pages"
    )

    print("\n[Step 4] Validating architecture...")

    validate_architecture(
        architecture
    )

    print("  ✓ Architecture is valid")

    print("\n[Step 5] Saving architecture...")

    save_architecture(
        architecture
    )

    print(
        f"  ✓ Saved: {ARCHITECTURE_PATH}"
    )

    print("\n" + "=" * 60)
    print("        V0.2 ARCHITECTURE COMPLETE")
    print("=" * 60)

    return architecture


if __name__ == "__main__":
    run_v02_architecture()